// continent: 'EU' | 'AS' | 'AF' | 'NA' | 'SA' | 'OC'
export const COUNTRIES = {
  "004": { tr: "Afganistan",               continent: "AS", variants: ["afganistan"] },
  "008": { tr: "Arnavutluk",               continent: "EU", variants: ["arnavutluk"] },
  "012": { tr: "Cezayir",                  continent: "AF", variants: ["cezayir"] },
  "024": { tr: "Angola",                   continent: "AF", variants: ["angola"] },
  "031": { tr: "Azerbaycan",               continent: "AS", variants: ["azerbaycan"] },
  "032": { tr: "Arjantin",                 continent: "SA", variants: ["arjantin"] },
  "036": { tr: "Avustralya",               continent: "OC", variants: ["avustralya"] },
  "040": { tr: "Avusturya",                continent: "EU", variants: ["avusturya"] },
  "048": { tr: "Bahreyn",                  continent: "AS", variants: ["bahreyn"] },
  "050": { tr: "Bangladeş",               continent: "AS", variants: ["bangladeş", "banglade"] },
  "051": { tr: "Ermenistan",               continent: "AS", variants: ["ermenistan"] },
  "056": { tr: "Belçika",                 continent: "EU", variants: ["belçika", "belcika"] },
  "064": { tr: "Butan",                    continent: "AS", variants: ["butan"] },
  "068": { tr: "Bolivya",                  continent: "SA", variants: ["bolivya"] },
  "070": { tr: "Bosna Hersek",             continent: "EU", variants: ["bosna hersek", "bosna-hersek", "bosna"] },
  "072": { tr: "Botsvana",                 continent: "AF", variants: ["botsvana", "botswana"] },
  "076": { tr: "Brezilya",                 continent: "SA", variants: ["brezilya"] },
  "090": { tr: "Solomon Adaları",         continent: "OC", variants: ["solomon adaları", "solomon"] },
  "100": { tr: "Bulgaristan",              continent: "EU", variants: ["bulgaristan"] },
  "104": { tr: "Myanmar",                  continent: "AS", variants: ["myanmar", "burma"] },
  "108": { tr: "Burundi",                  continent: "AF", variants: ["burundi"] },
  "112": { tr: "Belarus",                  continent: "EU", variants: ["belarus"] },
  "116": { tr: "Kamboçya",               continent: "AS", variants: ["kamboçya", "kambocya"] },
  "120": { tr: "Kamerun",                  continent: "AF", variants: ["kamerun"] },
  "124": { tr: "Kanada",                   continent: "NA", variants: ["kanada"] },
  "140": { tr: "Orta Afrika Cumhuriyeti",  continent: "AF", variants: ["orta afrika cumhuriyeti", "orta afrika"] },
  "144": { tr: "Sri Lanka",               continent: "AS", variants: ["sri lanka", "srilanka"] },
  "152": { tr: "Şili",                    continent: "SA", variants: ["şili", "sili", "chile"] },
  "148": { tr: "Çad",                     continent: "AF", variants: ["çad", "chad"] },
  "156": { tr: "Çin",                     continent: "AS", variants: ["çin", "cin", "china"] },
  "158": { tr: "Tayvan",                  continent: "AS", variants: ["tayvan", "taiwan"] },
  "170": { tr: "Kolombiya",               continent: "SA", variants: ["kolombiya"] },
  "174": { tr: "Mayotte",                  continent: "AF", variants: ["mayotte"] },
  "178": { tr: "Kongo Cumhuriyeti",        continent: "AF", variants: ["kongo cumhuriyeti", "kongo brazzaville"] },
  "180": { tr: "Demokratik Kongo",         continent: "AF", variants: ["demokratik kongo", "kongo", "demokratik kongo cumhuriyeti", "drc", "zaire"] },
  "188": { tr: "Kosta Rika",              continent: "NA", variants: ["kosta rika", "kostarika"] },
  "191": { tr: "Hırvatistan",            continent: "EU", variants: ["hırvatistan", "hirvatistan"] },
  "192": { tr: "Küba",                    continent: "NA", variants: ["küba", "kuba"] },
  "196": { tr: "Kıbrıs",                 continent: "EU", variants: ["kıbrıs", "kibris"] },
  "203": { tr: "Çekya",                   continent: "EU", variants: ["çekya", "cekya", "çek cumhuriyeti"] },
  "204": { tr: "Benin",                    continent: "AF", variants: ["benin"] },
  "208": { tr: "Danimarka",               continent: "EU", variants: ["danimarka"] },
  "214": { tr: "Dominik Cumhuriyeti",      continent: "NA", variants: ["dominik cumhuriyeti", "dominik"] },
  "218": { tr: "Ekvador",                  continent: "SA", variants: ["ekvador"] },
  "222": { tr: "El Salvador",              continent: "NA", variants: ["el salvador", "salvador"] },
  "226": { tr: "Ekvator Ginesi",           continent: "AF", variants: ["ekvator ginesi"] },
  "231": { tr: "Etiyopya",                 continent: "AF", variants: ["etiyopya"] },
  "232": { tr: "Eritre",                   continent: "AF", variants: ["eritre"] },
  "233": { tr: "Estonya",                  continent: "EU", variants: ["estonya"] },
  "242": { tr: "Fiji",                     continent: "OC", variants: ["fiji"] },
  "246": { tr: "Finlandiya",               continent: "EU", variants: ["finlandiya"] },
  "250": { tr: "Fransa",                   continent: "EU", variants: ["fransa"] },
  "262": { tr: "Cibuti",                   continent: "AF", variants: ["cibuti"] },
  "266": { tr: "Gabon",                    continent: "AF", variants: ["gabon"] },
  "268": { tr: "Gürcistan",               continent: "AS", variants: ["gürcistan", "gurcistan"] },
  "270": { tr: "Gambiya",                  continent: "AF", variants: ["gambiya"] },
  "276": { tr: "Almanya",                  continent: "EU", variants: ["almanya"] },
  "288": { tr: "Gana",                     continent: "AF", variants: ["gana"] },
  "300": { tr: "Yunanistan",               continent: "EU", variants: ["yunanistan"] },
  "304": { tr: "Grönland",                 continent: "NA", variants: ["grönland", "gronland", "greenland"] },
  "320": { tr: "Guatemala",                continent: "NA", variants: ["guatemala"] },
  "324": { tr: "Gine",                     continent: "AF", variants: ["gine"] },
  "328": { tr: "Guyana",                   continent: "SA", variants: ["guyana"] },
  "340": { tr: "Honduras",                 continent: "NA", variants: ["honduras"] },
  "348": { tr: "Macaristan",               continent: "EU", variants: ["macaristan"] },
  "352": { tr: "İzlanda",                 continent: "EU", variants: ["izlanda", "i̇zlanda"] },
  "356": { tr: "Hindistan",                continent: "AS", variants: ["hindistan"] },
  "360": { tr: "Endonezya",               continent: "AS", variants: ["endonezya"] },
  "364": { tr: "İran",                    continent: "AS", variants: ["iran", "i̇ran"] },
  "368": { tr: "Irak",                     continent: "AS", variants: ["irak"] },
  "372": { tr: "İrlanda",                 continent: "EU", variants: ["irlanda", "i̇rlanda"] },
  "376": { tr: "İsrail",                  continent: "AS", variants: ["israil", "i̇srail"] },
  "380": { tr: "İtalya",                  continent: "EU", variants: ["italya", "i̇talya"] },
  "384": { tr: "Fildişi Sahili",         continent: "AF", variants: ["fildişi sahili", "fildisi sahili", "kot divuar"] },
  "388": { tr: "Jamaika",                  continent: "NA", variants: ["jamaika"] },
  "392": { tr: "Japonya",                  continent: "AS", variants: ["japonya"] },
  "383": { tr: "Kosova",                   continent: "EU", variants: ["kosova", "kosovo"] },
  "398": { tr: "Kazakistan",               continent: "AS", variants: ["kazakistan"] },
  "400": { tr: "Ürdün",                   continent: "AS", variants: ["ürdün", "urdun"] },
  "404": { tr: "Kenya",                    continent: "AF", variants: ["kenya"] },
  "408": { tr: "Kuzey Kore",              continent: "AS", variants: ["kuzey kore"] },
  "410": { tr: "Güney Kore",              continent: "AS", variants: ["güney kore", "guney kore"] },
  "414": { tr: "Kuveyt",                   continent: "AS", variants: ["kuveyt"] },
  "417": { tr: "Kırgızistan",            continent: "AS", variants: ["kırgızistan", "kirgizistan"] },
  "418": { tr: "Laos",                     continent: "AS", variants: ["laos"] },
  "422": { tr: "Lübnan",                  continent: "AS", variants: ["lübnan", "lubnan"] },
  "426": { tr: "Lesoto",                   continent: "AF", variants: ["lesoto"] },
  "428": { tr: "Letonya",                  continent: "EU", variants: ["letonya"] },
  "430": { tr: "Liberya",                  continent: "AF", variants: ["liberya"] },
  "434": { tr: "Libya",                    continent: "AF", variants: ["libya"] },
  "440": { tr: "Litvanya",                 continent: "EU", variants: ["litvanya"] },
  "442": { tr: "Lüksemburg",              continent: "EU", variants: ["lüksemburg", "luksemburg"] },
  "450": { tr: "Madagaskar",               continent: "AF", variants: ["madagaskar"] },
  "454": { tr: "Malavi",                   continent: "AF", variants: ["malavi"] },
  "458": { tr: "Malezya",                  continent: "AS", variants: ["malezya"] },
  "466": { tr: "Mali",                     continent: "AF", variants: ["mali"] },
  "478": { tr: "Moritanya",               continent: "AF", variants: ["moritanya"] },
  "480": { tr: "Mauritius",               continent: "AF", variants: ["mauritius", "morityus"] },
  "484": { tr: "Meksika",                  continent: "NA", variants: ["meksika"] },
  "496": { tr: "Moğolistan",             continent: "AS", variants: ["moğolistan", "mogolistan"] },
  "498": { tr: "Moldova",                  continent: "EU", variants: ["moldova"] },
  "499": { tr: "Karadağ",                continent: "EU", variants: ["karadağ", "karadag"] },
  "504": { tr: "Fas",                      continent: "AF", variants: ["fas", "morocco"] },
  "508": { tr: "Mozambik",                 continent: "AF", variants: ["mozambik"] },
  "512": { tr: "Umman",                    continent: "AS", variants: ["umman"] },
  "516": { tr: "Namibya",                  continent: "AF", variants: ["namibya"] },
  "524": { tr: "Nepal",                    continent: "AS", variants: ["nepal"] },
  "528": { tr: "Hollanda",                 continent: "EU", variants: ["hollanda", "netherlands"] },
  "540": { tr: "Yeni Kaledonya",           continent: "OC", variants: ["yeni kaledonya"] },
  "548": { tr: "Vanuatu",                  continent: "OC", variants: ["vanuatu"] },
  "554": { tr: "Yeni Zelanda",            continent: "OC", variants: ["yeni zelanda", "yenizelanda"] },
  "558": { tr: "Nikaragua",               continent: "NA", variants: ["nikaragua"] },
  "562": { tr: "Nijer",                    continent: "AF", variants: ["nijer"] },
  "566": { tr: "Nijerya",                  continent: "AF", variants: ["nijerya"] },
  "578": { tr: "Norveç",                  continent: "EU", variants: ["norveç", "norvec"] },
  "586": { tr: "Pakistan",                 continent: "AS", variants: ["pakistan"] },
  "591": { tr: "Panama",                   continent: "NA", variants: ["panama"] },
  "598": { tr: "Papua Yeni Gine",          continent: "OC", variants: ["papua yeni gine", "papua"] },
  "600": { tr: "Paraguay",                 continent: "SA", variants: ["paraguay"] },
  "604": { tr: "Peru",                     continent: "SA", variants: ["peru"] },
  "608": { tr: "Filipinler",               continent: "AS", variants: ["filipinler"] },
  "616": { tr: "Polonya",                  continent: "EU", variants: ["polonya"] },
  "620": { tr: "Portekiz",                 continent: "EU", variants: ["portekiz"] },
  "624": { tr: "Gine-Bissau",              continent: "AF", variants: ["gine bissau", "gine-bissau"] },
  "630": { tr: "Porto Riko",              continent: "NA", variants: ["porto riko", "portoriko"] },
  "634": { tr: "Katar",                    continent: "AS", variants: ["katar"] },
  "638": { tr: "Réunion",                 continent: "AF", variants: ["reunion", "réunion"] },
  "642": { tr: "Romanya",                  continent: "EU", variants: ["romanya"] },
  "643": { tr: "Rusya",                    continent: "EU", variants: ["rusya"] },
  "646": { tr: "Ruanda",                   continent: "AF", variants: ["ruanda"] },
  "678": { tr: "Sao Tome ve Principe",     continent: "AF", variants: ["sao tome", "sao tome ve principe"] },
  "682": { tr: "Suudi Arabistan",          continent: "AS", variants: ["suudi arabistan", "suudi"] },
  "686": { tr: "Senegal",                  continent: "AF", variants: ["senegal"] },
  "688": { tr: "Sırbistan",              continent: "EU", variants: ["sırbistan", "sirbistan"] },
  "690": { tr: "Seyşeller",              continent: "AF", variants: ["seyşeller", "seyseller"] },
  "694": { tr: "Sierra Leone",             continent: "AF", variants: ["sierra leone", "sierraleone"] },
  "703": { tr: "Slovakya",                 continent: "EU", variants: ["slovakya"] },
  "704": { tr: "Vietnam",                  continent: "AS", variants: ["vietnam"] },
  "705": { tr: "Slovenya",                 continent: "EU", variants: ["slovenya"] },
  "706": { tr: "Somali",                   continent: "AF", variants: ["somali"] },
  "710": { tr: "Güney Afrika",            continent: "AF", variants: ["güney afrika", "guney afrika"] },
  "716": { tr: "Zimbabwe",                 continent: "AF", variants: ["zimbabwe", "zimbabve"] },
  "724": { tr: "İspanya",                 continent: "EU", variants: ["ispanya", "i̇spanya"] },
  "728": { tr: "Güney Sudan",             continent: "AF", variants: ["güney sudan", "guney sudan"] },
  "729": { tr: "Sudan",                    continent: "AF", variants: ["sudan"] },
  "740": { tr: "Surinam",                  continent: "SA", variants: ["surinam"] },
  "748": { tr: "Esvatini",                 continent: "AF", variants: ["esvatini", "svaziland"] },
  "752": { tr: "İsveç",                   continent: "EU", variants: ["isvec", "i̇sveç", "isveç"] },
  "756": { tr: "İsviçre",                continent: "EU", variants: ["isviçre", "i̇sviçre", "isvicre"] },
  "760": { tr: "Suriye",                   continent: "AS", variants: ["suriye"] },
  "762": { tr: "Tacikistan",               continent: "AS", variants: ["tacikistan"] },
  "764": { tr: "Tayland",                  continent: "AS", variants: ["tayland"] },
  "768": { tr: "Togo",                     continent: "AF", variants: ["togo"] },
  "784": { tr: "BAE",                      continent: "AS", variants: ["bae", "birleşik arap emirlikleri", "birlesik arap emirlikleri"] },
  "788": { tr: "Tunus",                    continent: "AF", variants: ["tunus"] },
  "792": { tr: "Türkiye",                 continent: "AS", variants: ["türkiye", "turkiye"] },
  "795": { tr: "Türkmenistan",            continent: "AS", variants: ["türkmenistan", "turkmenistan"] },
  "800": { tr: "Uganda",                   continent: "AF", variants: ["uganda"] },
  "804": { tr: "Ukrayna",                  continent: "EU", variants: ["ukrayna"] },
  "807": { tr: "Kuzey Makedonya",          continent: "EU", variants: ["kuzey makedonya", "makedonya"] },
  "818": { tr: "Mısır",                   continent: "AF", variants: ["mısır", "misir"] },
  "826": { tr: "Birleşik Krallık",       continent: "EU", variants: ["birleşik krallık", "ingiltere", "i̇ngiltere", "birlesik krallik"] },
  "834": { tr: "Tanzanya",                 continent: "AF", variants: ["tanzanya"] },
  "840": { tr: "ABD",                      continent: "NA", variants: ["abd", "amerika", "birleşik devletler", "birlesik devletler"] },
  "854": { tr: "Burkina Faso",             continent: "AF", variants: ["burkina faso"] },
  "858": { tr: "Uruguay",                  continent: "SA", variants: ["uruguay"] },
  "860": { tr: "Özbekistan",             continent: "AS", variants: ["özbekistan", "ozbekistan"] },
  "862": { tr: "Venezuela",               continent: "SA", variants: ["venezuela"] },
  "887": { tr: "Yemen",                    continent: "AS", variants: ["yemen"] },
  "894": { tr: "Zambiya",                  continent: "AF", variants: ["zambiya"] },
};

export const CONTINENTS = [
  { key: "EU", label: "Avrupa",        color: "#3b82f6" },
  { key: "AS", label: "Asya",          color: "#8b5cf6" },
  { key: "AF", label: "Afrika",        color: "#f59e0b" },
  { key: "NA", label: "Kuzey Amerika", color: "#ef4444" },
  { key: "SA", label: "Güney Amerika", color: "#10b981" },
  { key: "OC", label: "Okyanusya",     color: "#06b6d4" },
];

export function normalize(str) {
  return str.trim().toLowerCase()
    .replace(/i̇/g, 'i')  // İ → i (combining dot)
    .replace(/ı/g, 'i');  // ı → i (dotless)
}

export function matchCountry(input, guessed) {
  const norm = normalize(input);
  if (!norm) return null;
  for (const [code, country] of Object.entries(COUNTRIES)) {
    if (guessed.has(code)) continue;
    if (country.variants.some(v => normalize(v) === norm)) {
      return code;
    }
  }
  return null;
}

export const TOTAL_COUNTRIES = Object.keys(COUNTRIES).length;
